<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Course Report - {{ $courseData['title'] }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #4CAF50;
            margin: 0;
        }
        .header p {
            color: #666;
            margin: 5px 0;
        }
        .section {
            margin-bottom: 20px;
        }
        .section h2 {
            color: #4CAF50;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        .stats {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .stat-box {
            background: #f9f9f9;
            padding: 15px;
            border-radius: 5px;
            width: 23%;
            text-align: center;
        }
        .stat-box h3 {
            margin: 0;
            color: #666;
            font-size: 14px;
        }
        .stat-box p {
            margin: 5px 0 0;
            font-size: 24px;
            font-weight: bold;
            color: #4CAF50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            padding: 10px;
            border: 1px solid #ddd;
            text-align: left;
        }
        th {
            background: #f5f5f5;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Course Report</h1>
        <p>{{ $courseData['title'] }}</p>
        <p>Generated on: {{ $courseData['generated_at'] }}</p>
    </div>

    <div class="section">
        <h2>Course Overview</h2>
        <div class="stats">
            <div class="stat-box">
                <h3>Total Enrolled</h3>
                <p>{{ $courseData['enrolled_count'] }}</p>
            </div>
            <div class="stat-box">
                <h3>Completed</h3>
                <p>{{ $courseData['completed_count'] }}</p>
            </div>
            <div class="stat-box">
                <h3>In Progress</h3>
                <p>{{ $courseData['in_progress_count'] }}</p>
            </div>
            <div class="stat-box">
                <h3>Average Progress</h3>
                <p>{{ $courseData['average_progress'] }}%</p>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Enrolled Employees</h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Department</th>
                    <th>Progress</th>
                    <th>Status</th>
                    <th>Last Activity</th>
                    <th>Time Spent</th>
                </tr>
            </thead>
            <tbody>
                @foreach($courseData['enrolled_employees'] as $employee)
                <tr>
                    <td>{{ $employee['name'] }}</td>
                    <td>{{ $employee['department'] }}</td>
                    <td>{{ $employee['progress'] }}%</td>
                    <td>{{ $employee['is_completed'] ? 'Completed' : 'In Progress' }}</td>
                    <td>{{ $employee['last_activity'] }}</td>
                    <td>{{ $employee['time_spent'] }} hours</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>This report was automatically generated by SkillUp Learning Management System</p>
    </div>
</body>
</html> 